=== MeirzhanRymbayev/XMLApp/src/main/resources/TouristVoucher.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.com/tourist"
           xmlns="http://www.example.com/tourist"
           elementFormDefault="qualified"
           xmlns:hc="http://www.example.com/hotel">
    <xs:element name="TouristVoucher" type="touristVouchersType"/>


    <xs:element name="id">
        <xs:simpleType>
            <xs:restriction base="xs:ID">
                <xs:pattern value="[v]-[0-9]+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="dayAndNightQuantity">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]+[/][0-9]+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>


    <xs:simpleType name="typeOfTour">
        <xs:restriction base="xs:string">
            <xs:enumeration value="rest"/>
            <xs:enumeration value="pilgrimage"/>
            <xs:enumeration value="weekendsRest"/>
            <xs:enumeration value="excursionRest"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="transport">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="railway"/>
                <xs:enumeration value="plane"/>
                <xs:enumeration value="auto"/>
                <xs:enumeration value="liner"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>


    <xs:complexType name="hotelType">
        <xs:sequence>
            <xs:element name="stars" type="hc:hotelStars" />
            <xs:element name="food" type="hc:food"/>
            <xs:element name="room" type="hc:room"/>
            <xs:element name="tv" type="hc:TV"/>
            <xs:element name="airConditioning" type="hc:AirConditioner"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="currency">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="KZT"/>
                <xs:enumeration value="USD"/>
                <xs:enumeration value="EUR"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="cost">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="price" type="xs:positiveInteger"/>
                <xs:element ref="currency"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="voucherType">
        <xs:sequence>
            <xs:element ref="id"/>
            <xs:element type="typeOfTour" name="typeOfTour"/>
            <xs:element type="xs:string" name="country"/>
            <xs:element ref="dayAndNightQuantity"/>
            <xs:element ref="transport"/>
            <xs:element type="hotelType" name="hotel"/>
            <xs:element ref="cost"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="touristVouchersType">
        <xs:sequence>
            <xs:element type="voucherType" name="voucher" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== MeirzhanRymbayev/XMLApp/src/main/resources/TouristVoucher.xml
<?xml version="1.0" encoding="utf-8"?>
<TouristVoucher xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns="http://www.example.com/tourist"
                xsi:schemaLocation='http://www.example.com/tourist TouristVoucher.xsd'>
    <voucher>
        <id>v-1</id>
        <typeOfTour>pilgrimage</typeOfTour>
        <country>UAE</country>
        <dayAndNightQuantity>7/8</dayAndNightQuantity>
        <transport>plane</transport>
        <hotel>
            <stars>5</stars>
            <food></food>
            <room>2</room>
            <tv>true</tv>
            <airConditioning>true</airConditioning>
        </hotel>
        <cost>
            <price>1000</price>
            <currency>USD</currency>
        </cost>
    </voucher>
    <voucher>
        <id>v-2</id>
        <typeOfTour>rest</typeOfTour>
        <country>Spain</country>
        <dayAndNightQuantity>10/9</dayAndNightQuantity>
        <transport>railway</transport>
        <hotel>
            <stars>4</stars>
            <food>A1</food>
            <room>1</room>
            <tv>true</tv>
            <airConditioning>true</airConditioning>
        </hotel>
        <cost>
            <price>850</price>
            <currency>EUR</currency>
        </cost>
    </voucher>

</TouristVoucher>
